import {Dimensions, Platform, StyleSheet} from 'react-native';
import Colors from './Colors';
import {normalizeSize, rem} from './CommonFun';

const {height, width} = Dimensions.get('window');
// const brandingStyle = {}
const GlobalStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.onPrimary},
  pageContainer: {flex: 1, padding: rem(16)},
  bodyText: {color: Colors.bodyTextColor, fontSize: normalizeSize(12)},
  loginMainCont: {flex: 1, padding: rem(16), backgroundColor: Colors.onPrimary},
  mt10AlCenter: {marginTop: rem(10), alignItems: 'center'},
  alCenter: {alignItems: 'center', justifyContent: 'center'},
  alEnd: {alignItems: 'flex-end'},
  spaceContainer: {flex: 1, justifyContent: 'space-between', padding: rem(16)},
  flRowAlCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paddingContainer: {padding: rem(16), backgroundColor: Colors.onPrimary},

  DefaultErrorStyle: {
    fontSize: normalizeSize(11),
    height: normalizeSize(12),
    margin: 0,
    marginTop: 3,
    color: Colors.error,
  },
  IPIconDefaultContainerStyle: {
    height: 'auto',
    position: 'absolute',
    right: 10,
    marginVertical: 0,
    paddingHorizontal: height / 100,
  },
  IPIconDefaultLeftContainerStyle: {
    height: 'auto',
    position: 'absolute',
    left: 10,
    marginVertical: 0,
    paddingHorizontal: height / 100,
  },
  //Input Styles
  inputContainer: {marginTop: 5, paddingHorizontal: 0},
  errorBorder: {borderColor: Colors.error},
  jw10: {width: '10%'},
  w20: {width: '20%'},
  w15: {width: '15%'},
  w25: {width: '25%'},
  w30: {width: '30%'},
  w33: {width: '33.33%'},
  w35: {width: '35%'},
  w40: {width: '40%'},
  w45: {width: '45%'},
  w48: {width: '48%'},
  w50: {width: '50%'},
  w60: {width: '60%'},
  w70: {width: '70%'},
  w75: {width: '75%'},
  w80: {width: '80%'},
  w85: {width: '85%'},
  w90: {width: '90%'},
  w95: {width: '95%'},
  w97: {width: '97%'},
  w98: {width: '98%'},
  w99: {width: '99%'},
  w100: {width: '100%'},
  w500: {width: 500},
  mt8: {marginTop: '8%'},
  halfRight: {marginLeft: '4%', width: '48%'},
  halfRight1: {marginLeft: '4%', width: '40%'},

  mh20: {marginLeft: 20, marginRight: 20},
  mh10: {marginLeft: 10, marginRight: 10},
  mh11: {marginLeft: 11, marginRight: 11},
  mh5: {marginLeft: 5, marginRight: 5},
  ph20: {paddingLeft: 20, paddingRight: 20},
  ph10: {paddingLeft: 10, paddingRight: 10},
  ph11: {paddingLeft: 11, paddingRight: 11},
  ph5: {paddingLeft: 5, paddingRight: 5},
  mt0: {marginTop: 0},
  mt5: {marginTop: 5},
  mt10: {marginTop: 10},
  mt15: {marginTop: 15},
  mt20: {marginTop: 20},
  mt_20: {marginTop: normalizeSize(20)},
  mt30: {marginTop: 30},
  mt_30: {marginTop: normalizeSize(30)},
  mt40: {marginTop: 40},
  mt50: {marginTop: 50},
  mt100: {marginTop: 100},
  mb0: {marginBottom: 0},
  mb10: {marginBottom: 10},
  mb20: {marginBottom: 20},
  p0: {padding: 0},
  p0: {padding: rem(5)},
  p5: {padding: rem(10)},
  p30: {padding: 30},
  pb0: {paddingBottom: 0},
  pb5: {paddingBottom: 5},
  pb10: {paddingBottom: 10},
  pb20: {paddingBottom: 20},
  pt0: {paddingTop: 0},
  pt5: {paddingTop: 5},
  pt10: {paddingTop: 10},
  pt20: {paddingTop: 20},
  m10: {margin: 10},
  mv5: {marginVertical: 5},
  mv7: {marginVertical: 7},
  mv10: {marginVertical: 10},
  mv_10: {marginVertical: normalizeSize(10)},
  mv15: {marginVertical: 15},
  mv20: {marginVertical: 20},
  mv30: {marginVertical: 30},
  mv40: {marginVertical: 40},
  pv5: {paddingVertical: 5},
  pv10: {paddingVertical: 10},
  pv20: {paddingVertical: 20},
  pv25: {paddingVertical: 25},
  pv30: {paddingVertical: 30},
  pv40: {paddingVertical: 40},
  ml0: {marginLeft: 0},
  ml5: {marginLeft: 5},
  ml_5: {marginLeft: normalizeSize(5)},
  ml_10: {marginLeft: normalizeSize(10)},
  ml_15: {marginLeft: normalizeSize(15)},
  ml_20: {marginLeft: normalizeSize(20)},
  ml10: {marginLeft: 10},
  ml20: {marginLeft: 20},
  ml30: {marginLeft: 30},
  ml40: {marginLeft: 40},
  mr10: {marginRight: 10},
  mr20: {marginRight: 20},
  mr30: {marginRight: 30},
  mr40: {marginRight: 40},
  pl0: {paddingLeft: 0},
  pl10: {paddingLeft: 10},
  pl20: {paddingLeft: 20},
  jcenter: {justifyContent: 'center'},

  alSelfCenter: {alignSelf: 'center'},
  flRowalSelfCenterACenter: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  jSpaceBetween: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
  },
  flEnd: {alignSelf: 'flex-end'},
  fw5: {fontWeight: '500'},
  fw6: {fontWeight: '600'},
  fw7:{fontWeight: '700'},
  fw8:{fontWeight: '800'},
  fw9:{fontWeight:'bold'},
  w100H100: {width: '100%', height: '100%'},
  fs13: {fontSize: normalizeSize(13)},
  fs14: {fontSize: normalizeSize(14)},
  fs15: {fontSize: normalizeSize(15)},
  fs16: {fontSize: normalizeSize(16)},
  fs17: {fontSize: normalizeSize(18)},
  flRow: {flexDirection: 'row'},
  z9: {zIndex: 9999},
  z_9: {zIndex: -9999},
  h1_5: {height: height / 1.5},
  h2_5: {height: height / 2.5},
  h2_1: {height: height / 2.1},

  //refer Styles
  w50H50: {width: 50, height: 50},
  w40H40: {width: 40, height: 40},
  w30H30: {width: 30, height: 30},
  w20H20: {width: 20, height: 20},

  l_1: {flex: 0.1},
  w20h20: {width: 20, height: 20},
  w25h25: {width: 25, height: 25},
  w30h30: {width: 30, height: 30},
  w35h35: {width: 35, height: 35},
  w40h40: {width: 40, height: 40},
  w50h50: {width: 50, height: 50},
  mtH7: {marginTop: height / 7},
  flRowW100: {flexDirection: 'row', width: '100%'},
  mt25: {marginTop: normalizeSize(25)},
  bW0: {borderWidth: 0},
  colorWhite: {color: Colors.onPrimary},
  w100AlCenter: {width: '100%', alignSelf: 'center'},
  w100h150AlCenter: {width: '100%', height: height / 5, alignSelf: 'center'},
  careDeatil: {
    borderRadius: 5,
    margin: 10,
  },
  //CareBookList Styles

  //NoData
  noDataView: {
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    flex: 1,
  },
  noDataText: {
    padding: 35,
    fontSize: 20,
    color: '#7E7E7E',
    alignSelf: 'center',
    textAlign: 'center',
    lineHeight: 24,
  },
  noDataImg: {width: 200, alignSelf: 'center'},

  noDataView2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },

  noDataText1: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 24,
  },
  forgotView: {
    height: normalizeSize(40),
    paddingLeft: normalizeSize(8),
    borderRadius: 8,
    marginTop: 8,
    borderColor: '#000',
    elevation: 1,
    borderWidth: 0.5,
    backgroundColor: '#fff',
  },
  //Welcome
  welcomeView: {
    paddingVertical: 15,
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  welcomeView1: {
    flexDirection: 'row',
    paddingStart: normalizeSize(10),
    paddingBottom: normalizeSize(10),
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  welcomeIcon: {
    width: normalizeSize(25),
    resizeMode: 'cover',
    alignSelf: 'center',
  },
  welcomeView2: {marginLeft: normalizeSize(10), justifyContent: 'flex-start'},
  welcomeText: {
    padding: normalizeSize(10),
    fontWeight: '600',
    fontSize: normalizeSize(14),
  },
  templateView: {
    padding: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: Colors.devider,
  },
  commentsView1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  commentsText: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 24,
  },
  fileTreeIcon: {
    height: normalizeSize(20),
    width: normalizeSize(25),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  peopleTreeIcon: {
    height: normalizeSize(40),
    width: normalizeSize(40),
    resizeMode: 'contain',
    alignSelf: 'center',
  },

  medicineCard: {
    paddingVertical: 15,
    justifyContent: 'space-between',
    marginVertical: 0,
  },
  medicineCard2: {
    flexDirection: 'row',
    paddingStart: normalizeSize(10),
    paddingBottom: normalizeSize(10),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  medicineFile: {
    width: normalizeSize(25),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  medicineFile2: {
    marginLeft: normalizeSize(10),
    justifyContent: 'flex-start',
  },
  medicineFile3: {alignSelf: 'flex-end', marginRight: normalizeSize(10)},
  medicineFile4: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: normalizeSize(10),
  },
  medicineFile6: {
    padding: normalizeSize(10),
    fontSize: 16,
    color: 'black',
  },
  medicineFile8: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 24,
  },
  medicineFile11: {
    borderBottomWidth: 1,
    borderColor: Colors.devider,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 5,
  },

  //Modal
  homeModalCont: {},
  homeModalCont2: {
    height: '50%',
    paddingHorizontal: 10,
    backgroundColor: Colors.onPrimary,
  },
  homeModalCont20: {borderRadius: 10, backgroundColor: Colors.onPrimary},
  homeTransfer2: {alignItems: 'flex-end', paddingRight: normalizeSize(10)},

  //font
  font48_B_B: {fontSize: 48, color: 'white'},

  font36_B_B: {fontSize: 36, color: 'black'},
  font24_B_B: {fontSize: 24, color: 'black'},

  font20_B_B: {fontSize: 20, color: 'black'},
  font20_S_B: {fontSize: 20, color: 'black'},
  font20_M_B: {fontSize: 20, color: 'black'},

  font18_S_B: {fontSize: 18, color: 'black'},
  font18_M_W: {fontSize: 18, color: '#FFFFFF'},
  font18_R_B: {fontSize: 18, color: 'black'},
  font18_B_B: {fontSize: 18, color: 'black'},
  font18_M_B: {fontSize: 18, color: 'black'},
  font18_S_DG: {fontSize: 18, color: '#7E7E7E'},
  font18_R_DG: {fontSize: 18, color: '#7E7E7E'},

  font16_S_B: {fontSize: 16, color: 'black'},
  font16_S_GB: {fontSize: 16, color: '#333333'},
  font16_M_B: {fontSize: 16, color: 'black'},
  font16_S_W: {fontSize: 16, color: 'white'},
  font16_B_B: {fontSize: 16, color: 'black'},
  font16_R_B: {fontSize: 16, color: 'black'},
  font16_R_DG: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.38)',
  },
  font16_S_DG: {fontSize: 16, color: '#7E7E7E'},
  font16_S_LG: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  font16_R_LG: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  font16_M_LG: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  font16_B_LG: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.6)',
  },

  font15_S_B: {fontSize: 15, color: 'black'},
  font15_B_B: {fontSize: 15, color: 'black'},
  font15_S_W: {fontSize: 15, color: '#fff'},
  font15_M_B: {fontSize: 15, color: '#1A1A1A'},
  font15_R_DG: {fontSize: 15, color: '#7E7E7E'},
  font15_S_DG: {fontSize: 15, color: '#7E7E7E'},
  font15_R_B: {fontSize: 15, color: '#1A1A1A'},
  font15_R_W: {fontSize: 15, color: '#fff'},

  font14_S_B: {fontSize: 14, color: 'black'},
  font14_B_B: {fontSize: 14, color: 'black'},
  font14_S_W: {fontSize: 14, color: '#fff'},
  font14_M_B: {fontSize: 14, color: '#1A1A1A'},
  font14_R_DG: {fontSize: 14, color: '#7E7E7E'},
  font14_S_DG: {fontSize: 14, color: '#7E7E7E'},
  font14_R_B: {fontSize: 14, color: '#1A1A1A'},
  font14_R_W: {fontSize: 14, color: '#fff'},

  font15_R_BG: {fontSize: 15, color: '#333333'},
  font15_R_B60: {
    fontSize: 15,
    color: '#000000',
    opacity: 0.6,
  },
  font15_M_W: {fontSize: 15, color: '#FFFFFF'},

  font12_S_B: {fontSize: 12, color: 'black'},
  font12_R_G: {fontSize: 12, color: '#7E7E7E'},
});
export default GlobalStyles;